import type { ScheduledPost, CommentData, SystemStatus, OnboardingData } from './types';

export const defaultOnboarding: OnboardingData = {
  industry: 'Cosmic Travel & Orbital Lodging',
  goal: 'Drive bookings for the 2027 Aurora Space Cruise and boost orbital research membership',
  targetAudience: 'High-net-worth explorers, space science hobbyists, luxury adventure seekers',
  toneOfVoice: 'Visionary, scientific, luxurious, and bold',
};

export const defaultSystemStatus: SystemStatus = {
  instagramGraphApiConnected: true,
  metaGraphConnected: true,
  autopilotActive: false,
  pipelineHealth: 98,
};

// Seed video loop URLs (we can simulate using aesthetic CSS canvas elements or stock cosmic visual backgrounds)
export const spaceVideoLoops = [
  { id: 'neon-orbit', name: 'Neon Orbit Loop', color: 'from-purple-900 via-indigo-950 to-blue-900' },
  { id: 'solar-flare', name: 'Solar Flare Loop', color: 'from-red-950 via-orange-950 to-black' },
  { id: 'nebula-dust', name: 'Nebula Dust Loop', color: 'from-emerald-950 via-teal-950 to-blue-950' },
  { id: 'dark-matter', name: 'Dark Matter Pulse', color: 'from-slate-950 via-zinc-900 to-navy-dark' },
];

export const initialScheduledPosts: ScheduledPost[] = [
  {
    id: 'post-1',
    title: 'Earth Rise from Room 304',
    theme: 'Showcasing the premium luxury views from the Aurora Hotel suites.',
    imagePrompt: 'Photorealistic shot from a round cabin window of Earth rising over the lunar horizon, neon blue atmospheric haze, warm cabin interior lighting, shot on ARRI Alexa.',
    caption: 'Waking up to this. Earth rise from the comfort of our luxury suites. Ready to see the universe in a completely different light? Bookings now open for Q3 2027.',
    hashtags: ['spacecruise', 'aurorahotel', 'earthrise', 'cosmictravel', 'luxurytravel'],
    scheduledTime: '2026-05-26T09:00:00Z',
    platform: 'instagram-grid',
    status: 'scheduled',
    videoLoopUrl: 'neon-orbit',
    fontScale: 1.1,
    alignVector: 'bottom',
    layoutSeed: 1234,
  },
  {
    id: 'post-2',
    title: 'Microgravity Dining Experience',
    theme: 'Explaining the physics and elegance of luxury molecular gastronomy in space.',
    imagePrompt: 'Dynamic macro shot of floating glowing green mocktail droplets inside a sleek glass lounge, passengers smiling in zero-gravity in the background, neon green accents.',
    caption: 'Fine dining, elevated to zero gravity. Our orbital chefs have mastered the art of floating molecular cuisine. Experience flavors that literally dance before your eyes.',
    hashtags: ['spaceluxury', 'zeroGdining', 'moleculargastronomy', 'orbitalcruise', 'futurefood'],
    scheduledTime: '2026-05-27T15:30:00Z',
    platform: 'instagram-stories',
    status: 'scheduled',
    videoLoopUrl: 'nebula-dust',
    fontScale: 1.0,
    alignVector: 'center',
    layoutSeed: 5678,
  },
  {
    id: 'post-3',
    title: 'Orbital Research Labs Open Access',
    theme: 'Calling all citizen scientists to reserve lab hours on the next flight.',
    imagePrompt: 'Cinematic wide shot of a modern, glowing laboratory inside a space station. Scientists working on hydroponics under green LED lamps, neon accent pipes, deep space background through double-paned window.',
    caption: 'Science belongs to the daring. The Aurora Space Lab is opening research slots for civilian projects in 2027. Bring your experiments to low Earth orbit.',
    hashtags: ['citizenscience', 'orbitalresearch', 'auroraspace', 'microgravity', 'stemstars'],
    scheduledTime: '2026-05-28T10:15:00Z',
    platform: 'facebook',
    status: 'scheduled',
    videoLoopUrl: 'solar-flare',
    fontScale: 1.2,
    alignVector: 'top',
    layoutSeed: 9012,
  },
  {
    id: 'post-4',
    title: 'Preparing For Launch: Crew Training',
    theme: 'A sneak peek into the centrifuges and training routines for passengers.',
    imagePrompt: 'Action shot of a passenger smiling during a simulator session, wearing a sleek navy and neon green jumpsuit, futuristic hud displays in the background.',
    caption: 'Preparing your mind and body for the ultimate journey. Our comprehensive 3-day training program ensures you are flight-ready. Ready to feel the Gs?',
    hashtags: ['spacetraining', 'crewflight', 'astronautprep', 'adventuresports', 'orbitbound'],
    scheduledTime: '2026-05-29T18:00:00Z',
    platform: 'instagram-grid',
    status: 'scheduled',
    videoLoopUrl: 'dark-matter',
    fontScale: 1.0,
    alignVector: 'bottom',
    layoutSeed: 3456,
  },
  {
    id: 'post-5',
    title: 'The Silent Giant: Watching the Milky Way',
    theme: 'Focusing on the spiritual and psychological changes of the Overview Effect.',
    imagePrompt: 'Silhouetted astronaut looking out a massive cupola window into the glowing arms of the Milky Way galaxy, stars reflected on the helmet visor, absolute serene silence.',
    caption: 'The stars do not look bigger; they look brighter. Experience the Overview Effect that has changed the perspective of every astronaut. Your view of humanity will never be the same.',
    hashtags: ['overvieweffect', 'milkyway', 'deepspace', 'stellarview', 'mindfulspace'],
    scheduledTime: '2026-05-25T11:00:00Z', // Past scheduled time to show it was published
    platform: 'instagram-grid',
    status: 'published',
    videoLoopUrl: 'neon-orbit',
    fontScale: 1.0,
    alignVector: 'center',
    layoutSeed: 7890,
  }
];

export const initialComments: CommentData[] = [
  {
    id: 'comm-1',
    platform: 'instagram',
    username: 'astro_clara',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=100&q=80',
    commentText: 'How long is the training program? Do we need any prior scientific background to participate in the Aurora Lab slots?',
    timestamp: '2026-05-25T12:05:00Z',
    aiSuggestedReply: 'Hello @astro_clara! No prior scientific background is required. Our 3-day pre-flight training covers all safety and laboratory procedures. We also have flight scientists on board to guide you throughout!',
    status: 'pending',
    postId: 'post-3',
    postTitle: 'Orbital Research Labs Open Access',
  },
  {
    id: 'comm-2',
    platform: 'instagram',
    username: 'space_adventurer',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=100&q=80',
    commentText: 'Is the molecular dining menu included in the standard suite packages? Or is it an add-on?',
    timestamp: '2026-05-25T12:20:00Z',
    aiSuggestedReply: 'Hey @space_adventurer! The standard package includes our curated gourmet dining. The signature zero-G Molecular Experience can be reserved as an exclusive add-on during booking.',
    status: 'pending',
    postId: 'post-2',
    postTitle: 'Microgravity Dining Experience',
  },
  {
    id: 'comm-3',
    platform: 'facebook',
    username: 'Marcus Vance',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=100&q=80',
    commentText: 'This is absolutely mind-blowing. Bookings for Q3 2027 are open, but are deposit payments refundable if training is failed?',
    timestamp: '2026-05-25T12:45:00Z',
    aiSuggestedReply: 'Hi Marcus! Deposits are fully transferable to a later date. In the rare event of a medical or training disqualification, a 90% refund is issued. Details are in our Cosmic Booking Protection policy!',
    status: 'pending',
    postId: 'post-1',
    postTitle: 'Earth Rise from Room 304',
  },
  {
    id: 'comm-4',
    platform: 'instagram',
    username: 'galactic.wanderer',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=100&q=80',
    commentText: 'I would pay anything just to see the Milky Way from that cupola window. Pure magic.',
    timestamp: '2026-05-25T10:15:00Z',
    aiSuggestedReply: 'We agree @galactic.wanderer! It is truly magical. We hope to welcome you on board to experience it first-hand.',
    status: 'replied',
    postId: 'post-5',
    postTitle: 'The Silent Giant: Watching the Milky Way',
  }
];

export const sampleGeneratedIdeas: Omit<ScheduledPost, 'id' | 'scheduledTime' | 'status'>[] = [
  {
    title: 'Gravity Defying Wellness Sessions',
    theme: 'Detailing floating yoga and mindfulness therapy under orbital conditions.',
    imagePrompt: 'Zen-like composition of a cabin with warm amber backlighting. A passenger meditating in mid-air in front of a giant view window overlooking the curving blue planet.',
    caption: 'Find your center... completely suspended. Our Zero-G Mindfulness sessions allow you to float into deep meditation. True weightlessness for mind and body.',
    hashtags: ['spacewellness', 'orbitalyoga', 'mindfulflight', 'zerogravity', 'wellnessfuture'],
    videoLoopUrl: 'neon-orbit',
    fontScale: 1.05,
    alignVector: 'center',
    layoutSeed: 1111,
    platform: 'instagram-grid',
  },
  {
    title: 'The Engineering Behind the Aurora Station',
    theme: 'Explaining the dual-ring artificial gravity systems to reassure clients.',
    imagePrompt: 'Technical schematic overlay style on a rotating sleek orbital ring station. High-tech schematics in neon green lines showing rotational velocity vectors.',
    caption: 'Comfort meets cosmic physics. Learn how our dual-rotating rings generate comfortable 0.3G in the sleeping quarters, allowing for perfect rest while in deep space.',
    hashtags: ['spaceengineering', 'physicsfun', 'spacetech', 'aurorastation', 'futuretech'],
    videoLoopUrl: 'dark-matter',
    fontScale: 1.15,
    alignVector: 'bottom',
    layoutSeed: 2222,
    platform: 'instagram-grid',
  },
  {
    title: 'Astrophotography Mastery Class',
    theme: 'Teaching passengers how to capture stellar nebulae with on-board telescope arrays.',
    imagePrompt: 'Close up of a passenger adjusting a sleek, glowing digital focus ring on an astronomical viewfinder. Colorful nebulae reflecting off their eye, neon blue lighting.',
    caption: 'Capture the universe like never before. Access our high-resolution external telescope arrays and capture deep-space nebulae directly from your suite tablet.',
    hashtags: ['astrophotography', 'hubbleview', 'telescopelife', 'starsign', 'creativespace'],
    videoLoopUrl: 'nebula-dust',
    fontScale: 1.0,
    alignVector: 'top',
    layoutSeed: 3333,
    platform: 'instagram-grid',
  },
  {
    title: 'Cosmic Cocktails & Interstellar Lounges',
    theme: 'Showcasing the social atmosphere inside the Aurora primary viewing lounge.',
    imagePrompt: 'Cozy luxury lounge with curved padded seating, vibrant neon green light accents, retro-futuristic decor, guests laughing, giant windows showing stars.',
    caption: 'Sip on a "Supernova Splash" while cruising at 28,000 km/h. The Pulsar Lounge is where cosmic travelers share stories from across the globe.',
    hashtags: ['spacelounge', 'interstellarclub', 'nightlifefuture', 'travelcool', 'cosmosocial'],
    videoLoopUrl: 'solar-flare',
    fontScale: 0.95,
    alignVector: 'bottom',
    layoutSeed: 4444,
    platform: 'instagram-grid',
  },
  {
    title: 'Sustainable Space: Recycled Carbon Offsets',
    theme: 'Highlighting our zero-waste life support cycles and eco-friendly fuels.',
    imagePrompt: 'Macro shot of lush green microalgae bioreactors glowing with emerald light. Sleek chrome pipes feeding into water filtration units inside the station core.',
    caption: 'Cruising the stars, protecting our home. The Aurora Station operates on a 100% closed-loop ecological life support system, achieving true carbon neutrality.',
    hashtags: ['ecospace', 'closedloop', 'sustainablespace', 'greenfuture', 'cleanenergy'],
    videoLoopUrl: 'nebula-dust',
    fontScale: 1.1,
    alignVector: 'center',
    layoutSeed: 5555,
    platform: 'instagram-grid',
  }
];
